# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('qtd_times', models.PositiveIntegerField(verbose_name='Quantidade de times')),
                ('qtd_grupos', models.PositiveIntegerField(default=1, verbose_name='Quantidade de grupos')),
                ('formato', models.CharField(choices=[('C', 'Copa'), ('PC', 'Pontos corridos')], max_length=2, verbose_name='Formato')),
                ('equipes_cadastradas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('pontos', models.PositiveIntegerField(default=0, verbose_name='Pts')),
                ('vitorias', models.PositiveIntegerField(default=0, verbose_name='V')),
                ('empates', models.PositiveIntegerField(default=0, verbose_name='E')),
                ('derrotas', models.PositiveIntegerField(default=0, verbose_name='D')),
                ('gols_marcados', models.PositiveIntegerField(default=0, verbose_name='GP')),
                ('gols_sofridos', models.PositiveIntegerField(default=0, verbose_name='GC')),
                ('saldo_gols', models.PositiveIntegerField(default=0, verbose_name='SG')),
                ('campeonato', models.PositiveIntegerField(default=0, verbose_name='Campeonato')),
                ('emblema', models.ImageField(blank=True, null=True, upload_to='emblemas/', verbose_name='Emblema')),
            ],
            options={
                'ordering': ['-pontos', '-vitorias', '-empates', '-derrotas', '-saldo_gols'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('apelido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apelido')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('camisa', models.PositiveIntegerField(blank=True, null=True, verbose_name='N° Camisa')),
                ('rua', models.CharField(max_length=50, verbose_name='Rua')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('total_gols', models.PositiveIntegerField(default=0, verbose_name='Gols')),
                ('total_gols_contra', models.PositiveIntegerField(default=0, verbose_name='Gols contra')),
                ('total_cartoes_amarelos', models.PositiveIntegerField(default=0, verbose_name='Cartões amarelos')),
                ('total_cartoes_vermelhos', models.PositiveIntegerField(default=0, verbose_name='Cartões vermelhos')),
                ('cartoes_acumulados', models.PositiveIntegerField(default=0, verbose_name='Cartões acumulados')),
                ('disponivel', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('campeonato', models.PositiveIntegerField(default=0, verbose_name='Campeonato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipe', verbose_name='Equipe')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lance', models.CharField(choices=[('G', 'Gol'), ('GC', 'Gol contra'), ('CA', 'Cartão amarelo'), ('CV', 'Cartão vermelho')], max_length=2, verbose_name='Lance')),
                ('descricao', models.CharField(default='', max_length=200, verbose_name='Descrição')),
                ('tempo', models.PositiveIntegerField(default=0, verbose_name='Tempo')),
                ('minuto', models.PositiveIntegerField(default=0, verbose_name='Minuto')),
                ('equipe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Equipe', verbose_name='Equipe')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Jogador', verbose_name='Jogador')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodada', models.PositiveIntegerField(verbose_name='Rodada')),
                ('campeonato', models.PositiveIntegerField(default=None, verbose_name='Campeonato')),
                ('gols_mandante', models.PositiveIntegerField(default=0, verbose_name='Gols mandante')),
                ('gols_visitante', models.PositiveIntegerField(default=0, verbose_name='Gols visitante')),
                ('total_cart_amarelo', models.PositiveIntegerField(default=0, verbose_name='Cartões amarelos')),
                ('total_cart_vermelho', models.PositiveIntegerField(default=0, verbose_name='Cartões vermelhos')),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('finalizada', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Grupo', verbose_name='Grupo')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandante', to='app.Equipe', verbose_name='Mandante')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitante', to='app.Equipe', verbose_name='Visitante')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('conteudo', models.TextField(verbose_name='Conteudo')),
                ('imagem', models.ImageField(null=True, upload_to='imgPosts/', verbose_name='Imagem')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de criação')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Equipe', verbose_name='Equipe')),
            ],
        ),
        migrations.AddField(
            model_name='lance',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Partida', verbose_name='Partida'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Grupo', verbose_name='Grupo'),
        ),
    ]
