# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-21 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_partida_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='fase',
            field=models.CharField(choices=[('G', 'Grupos'), ('O', 'Oitavas'), ('Q', 'Quartas'), ('S', 'Semi-final'), ('F', 'Final')], default='G', max_length=1, verbose_name='Fase'),
        ),
    ]
