# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-21 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_partida_fase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='rodada',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rodada'),
        ),
    ]
