# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_partida_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partida',
            name='hora',
            field=models.CharField(blank=True, default='--:--', max_length=5, null=True, verbose_name='Hora'),
        ),
    ]
