# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180522_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='saldo_gols',
            field=models.IntegerField(default=0, verbose_name='SG'),
        ),
    ]
